name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame and Bloc.
version: 2.1.2
# homepage: https://github.com/Sproute777/bonfire

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  flame: ^1.0.0
  tiledjsonreader: 1.0.9
  http: 0.13.4
  a_star_algorithm: 0.2.1
  # flame_bloc: ^1.1.0

dev_dependencies:
  linter: ^1.18.0
  # flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
